Get Pettingzoo example to work again WiP.
flatland-association/flatland-rl pull request #102
Opened 2024-12-15 07:35 UTC by chenkins

## Changes

Describe the changes you made.

## Related issues

Link to every issue from the issue tracker (if any) you addressed in this PR.

## Checklist

- [ ] Tests are included for relevant behavior changes.
- [ ] Documentation is added in the `docs` folder for relevant behavior changes. If you made important user-facing
  changes, describe them under the `[Unreleased]` tag in `CHANGELOG.md`.
- [ ] New package dependencies are declared in the `pyproject.toml` file.
  Requirement files have been updated by running `tox -e requirements`.
- [ ] Code works with all supported Python versions (3.10, 3.11 and 3.12). Checks run with all three version and are
  required to run successfully.
- [ ] Code is formatted according to PEP 8 (an IDE like PyCharm can do this for you).
- [ ] Technical guidelines listed in `CONTRIBUTING.md` are followed.

2024-12-15 13:47 UTC, SergeCroise commented on flatland/ml/pettingzoo/examples/flatland_pettingzoo_stable_baselines.py
> +    # SB3 models are designed for single-agent settings, we get around this by using he same model for every agent
```suggestion
    # SB3 models are designed for single-agent settings, we get around this by using the same model for every agent
```

2025-02-16 15:34 UTC, chenkins commented on flatland/ml/pettingzoo/pettingzoo_parallel_rail_env.py
> +            # TODO bad smell: must be gymobservationbuilder
typing

2025-02-16 15:34 UTC, chenkins commented on flatland/ml/pettingzoo/wrappers.py
> +    # TODO should be AEC instead
AEC instead of parallel

2025-03-12 06:16 UTC, chenkins commented on tests/test_pettingzoo_interface.py
Add again example or test that is run in ci

2025-03-12 06:16 UTC, chenkins commented on flatland/ml/pettingzoo/examples/flatland_pettingzoo_stable_baselines.py
> +    # TODO not sure this is correct - what about use of AECEnv in the waterworld example?
TODO inference

2025-03-12 06:20 UTC, chenkins commented on flatland/contrib/training/flatland_pettingzoo_rllib.py
@manuschn We drop illustration of usage of pettingzoo with rllib as we directly provide rllib `MultiAgentEnv` (#85).

2025-03-12 06:22 UTC, chenkins commented on flatland/contrib/training/flatland_pettingzoo_stable_baselines.py
> -                     config={}, name=experiment_name, save_code=True)
Illustration of logging/callbacks incl. `wandb` will be added again with #77 / #76

2025-03-12 06:23 UTC, chenkins commented on flatland/ml/pettingzoo/examples/flatland_pettingzoo_stable_baselines.py
> +    eval(env_fn, num_games=2, render_mode="human", **env_kwargs)
Add to as test instead?

2025-03-15 23:13 UTC, manuschn requested changes

2025-03-16 07:25 UTC, chenkins commented on flatland/ml/pettingzoo/examples/flatland_pettingzoo_stable_baselines.py
> +    raw_env = env_generator(obs_builder_object=FlattenedNormalizedTreeObsForRailEnv(max_depth=3, predictor=ShortestPathPredictorForRailEnv(max_depth=50)))
too many of these mains dangling around #173

2025-03-16 09:36 UTC, manuschn approved these changes

2025-03-16 13:36 UTC, merged